### ISSUE TITLE
[workshops] missing workshops

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#1]
Hey @dungscout96, the workshop's index lists all workshops from the very 1st, while the menu on the side and markdown files only start from the 7th. Seems like these early workshops pages are not hosted on the wiki, see here for example:
https://sccn.ucsd.edu/eeglab/workshop04/
Is there anyway to convert them like the others?

**Comment by dungscout96** [comment]
It's fine to keep those workshops pages on the sccn server
