### ISSUE TITLE
Your awesome title

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#15]
Seems like all the page have the same tab "Your awesome title" and also at the top "Search your awesome title". Can we change that?

**Comment by arnodelorme** [comment]
<img width="982" alt="Screen Shot 2020-12-01 at 8 25 00 PM" src="https://user-images.githubusercontent.com/1872705/100836494-782a6780-3413-11eb-9feb-6e1b77c29854.png">

**Comment by dungscout96** [comment]
Fixed

**Comment by arnodelorme** [comment]
Cool that it was easy.
