### ISSUE TITLE
Image alignment

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#17]
I have replaced class float-right by align=right and got the same effect (image MoBIPoster.jpg)

https://sccn.github.io/workshops/Online_EEGLAB_Workshop.html

If you look at the HTML and reformat it pretty https://www.freeformatter.com/html-formatter.html you can see that the code is very simple and readable.

I think the issue with image alignment might have something to do with the theme and CSS styles for the page.

**Comment by dungscout96** [comment]
Images are now center-aligned by default with 28cc1dc
