### ISSUE TITLE
missing dataset

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#18]
The dataset used in the tutorial is missing:

https://sccn.github.io/tutorials/single-subject/loading-data-in-EEGLAB

**Comment by arnodelorme** [comment]
I removed the link

**Comment by claire-braboszcz** [comment]
But then... no dataset to use for the tutorial?

**Comment by arnodelorme** [comment]
It is the same as the one in EEGLAB sample_data folder. If you have EEGLAB you have it.

Arno
