### ISSUE TITLE
Installing Jekyll

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#20]
@dungscout96 would you mind to add documentation to the README.md file on how to install Jekyll on OSx and get a version running on your laptop for quick live update.

**Comment by dungscout96** [comment]
I added the instructions. Let me know if it you can install it smoothly!

**Comment by arnodelorme** [comment]
It works. Should I restart Jekyll every time I do a modification?

**Comment by dungscout96** [comment]
While jekyll serve still running it should automatically reload whenever you save any changes, except for changes to the _config file

**Comment by arnodelorme** [comment]
Wonderful. Thanks
