### ISSUE TITLE
links to eeglab function code

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#22]
@arnodelorme Do we want to update the links to eeglab code on github or do we remove them?

See for example  "This pops up the eegplot() the scrolling data display window below."
in https://sccn.github.io/tutorials/single-subject/loading-data-in-EEGLAB

**Comment by arnodelorme** [comment]
Yes, we want to keep it. The solution is fairly simple. On the old wiki, this calls a PHP function.

http://sccn.ucsd.edu/eeglab/locatefile.php?eeglab.m

Although I would need to revisit as it does not seem functional anymore (but we want to keep the links).

**Comment by dungscout96** [comment]
Fixed
