### ISSUE TITLE
Jekyll error - does not find layout  style

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#23]
Hi @dungscout96, I re-started my local jekyll server for the first time in a while and it is unhappy. See the warnings below. It results in the webpage not showing the menu on the side.  Would you have any idea how to fix this?

![jekyll_error](https://user-images.githubusercontent.com/914741/101053774-14717d00-3580-11eb-9b0e-fa86b78c8189.png)

NB: I updated the config file to "remote_theme: just-the-docs" 

Just before it occurred (and the reason why I restarted the server) I had this liquid error described here:
https://jekyllrb.com/docs/troubleshooting/#liquid
Not sure if it is related though! (I could fix this one).

**Comment by dungscout96** [comment]
Hi @claire-braboszcz, in *_config.yml* the line ``remote_theme: pmarsceill/just-the-docs`` should be changed to ``theme: "just-the-docs"``. **Don't commit this change to remote**. Let me know if that solves it

**Comment by claire-braboszcz** [comment]
Yeah I have it like this - actually updated it after the error occurred

**Comment by dungscout96** [comment]
Hmm, can you share your _config.yml file?

**Comment by claire-braboszcz** [comment]
Sure - I'll email it as don't seem to be able to attach it here

**Comment by claire-braboszcz** [comment]
I also tried removing the _site folder to rebuild it from scratch - but it didn't change anything
