### ISSUE TITLE
color class for function filenames

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#24]
Hey so as suggested before it would indeed be great if we could define a class to avoid having font color command for each time there's a function name mentioned in the text. We could put them in any colour apart from blue and red (already in use) I reckon

So far it appears like this: 
{ {File\|pop_topoplot.m} }

It would be easy enough for me to run a change al command once we have a class

Note that on the first 4 pages of tutorial I, I did a mistake and changed them to a link.. I'll get back to correct this later

**Comment by arnodelorme** [comment]
Yes, this is the same as the other issue. This is a macro that replaces with http://sccn.ucsd.edu/eeglab/locatefile.php?pop_topoplot.m

**Comment by dungscout96** [comment]
I can run a script to replace {{ File* }} with http://sccn.ucsd.edu/eeglab/locatefile.php?. Would that do it?

**Comment by arnodelorme** [comment]
I think it would

**Comment by dungscout96** [comment]
Fixed in 6bdb590
