### ISSUE TITLE
tutorial page I.7 missing parts?

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#25]
Hi @arnodelorme, is this page missing some bits? It does not say anything about comparing epochs as the title would suggest. 

https://sccn.github.io/tutorials/single-subject/selecting-data-epochs-and-comparing

**Comment by claire-braboszcz** [comment]
Just checked on the wiki, it does seem to be missing part of the elements:
https://sccn.ucsd.edu/wiki/Chapter_07:_Selecting_Data_Epochs_and_Comparing

@dungscout96 is it possible to selectively re-import this page only?

**Comment by arnodelorme** [comment]
I have updated the title but put a note somewhere in case we have to revisit it.

**Comment by dungscout96** [comment]
There are several versions for each tutorial pages on the wiki. I probably chose the wrong version to import as I was selecting them from a list of all page titles. I will reimport I.7. Can you keep an eye out for other tutorial pages in the Single subject chapter? @claire-braboszcz @arnodelorme 
I just added the Multi-subject tutorials and I went to each page on the wiki and copy the page title to make sure I got the pages right, so it should not be an issue from now.
