### ISSUE TITLE
tutorial I.8 erp images too long

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#26]
This tutorial is really long. I cut bits already that I put in the appendix for now.  @arnodelorme  would it make sense to have a section dedicated to working with ERPs and EEG spectral analysis where to move all sections starting from this one?
https://sccn.github.io/tutorials/single-subject/plotting-erp-images#sorting-trials-by-eeg-phase-value

**Comment by arnodelorme** [comment]
This is a good question. I think a section in appendix is fine with clear references between the 2 sections (the one in the main tutorial and the one in appendix).
