### ISSUE TITLE
collapsible text box for context content ?

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#28]
At the moment I am chucking a lot of theoretical/ background comments in the Appendix to help keep the tutorial light and focused on the EEGLAB interface. 
I wonder if it would not be better to put this text in "collapsible text boxes" that reader can open by pressing on a + sign if they want to know more about a topic ? I have no idea if we can do that with markdown though

**Comment by claire-braboszcz** [comment]
I found how to do it and tried it here:

https://sccn.github.io/tutorials/single-subject/inspecting-ica-comp.html

see "Note on ICA component projections and electrode montage plot"

However the markdown is not being interpreted within the html bloc.. Any idea how to fix this? @dungscout96

**Comment by dungscout96** [comment]
Thanks for finding out the <detail> tag! We'll just have to use pure html code within this block. I made edits for the links and the image file for that block for example.
