### ISSUE TITLE
Local copy theme behaving differently than the online one

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#32]
<img width="1071" alt="Screen Shot 2020-12-15 at 1 49 52 PM" src="https://user-images.githubusercontent.com/1872705/102286530-95b00480-3edc-11eb-9ea8-254a1cf54216.png">

**Comment by arnodelorme** [comment]
I still have this bug on my local copy

**Comment by dungscout96** [comment]
This happens for the live page as well if you resize the window to a point. It should disappear as you continue resizing it a bit further though (both local and live). I think this is a glitch happened after I increased the content width. I'll look more into it further.

**Comment by arnodelorme** [comment]
It does not happen for me on the live page, only on my computer
