### ISSUE TITLE
List of things to check

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#34]
Not sure how to put the colours back into this table:

https://sccn.github.io/tutorials/IV/IV.4_Exporting_Data.html

Also: why is the cell in the bottom line yellow and not green ?

Also see here for table with colours:
https://sccn.github.io/others/EEGLAB_vs._Commercial_EEG_Software.html

**Comment by arnodelorme** [comment]
We can make a list.

Arno

**Comment by claire-braboszcz** [comment]
STUDY part:
- decide on which studyset to use

**Comment by claire-braboszcz** [comment]
Using MRI file - screen captures are from SPM2. It seems similar to SPM8 so probably the interface didn't change much.
Current version is SPM12 - check if need to re do the screen captures

https://sccn.github.io/tutorials/misc/Using_custom_MRI_from_individual_subjects.html

**Comment by claire-braboszcz** [comment]
This page might not be useful anymore with the new tutorial structure:

Quick tutorial on rejecting data artifacts with EEGLAB
https://sccn.github.io/tutorials/misc/Quick_Tutorial_on_Rejection.html

I updated the formatting but not the content - waiting to see what we do with it

**Comment by arnodelorme** [comment]
Yes, let’s wait on this page. I will look at it today.

**Comment by claire-braboszcz** [comment]
High perf computing page to complete:
https://sccn.github.io/others/EEGLAB_and_high_performance_computing.html

**Comment by claire-braboszcz** [comment]
Channel locations in others: merge with chanloc tutorial ?

https://sccn.github.io/others/Channel_Location_Files.html

**Comment by claire-braboszcz** [comment]
Python vs Matlab:
I think you are "slightly" overdoing it here ;-) The Spyder IDE is a good equivalent of the Matlab interface 

" The closest alternative to the Matlab interactive interface is the
    Jupyter notebook environment that runs in your browser. Yet the
    graphical capabilities of Jupyter notebook are very limited (it is
    sometimes hard to manipulate figures, impossible to zoom, etc...).
    Also, all your code needs to be on one (very very long) page and it
    is hard to create subscripts or make your code modular. Executing
    blocks of code not in the order set in the notebook can be
    confusing. Most people we know who have used Matlab and tried
    Jupyter notebook hate Jupyter notebook - then learn to live with the
    limitations if they absolutely need it for their work.

**Comment by arnodelorme** [comment]
OK, we could add the Spyder IDE reference.

Arno

**Comment by claire-braboszcz** [comment]
BIDS: do we mention it on the tutorial ?
(checking if I can insert the video playlist somewhere!)

**Comment by arnodelorme** [comment]
We do not have a BIDS tutorial yet.
