### ISSUE TITLE
jekyll not updating section title

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#38]
Hi, I changed the title of the misc section but it doesn't seem to update on my local jekyll - pages are correctly not appearing under the old section title but the new "reference topic" section does not show up.

**Comment by arnodelorme** [comment]
That’s weird. I will have a look.

**Comment by dungscout96** [comment]
Hi Claire, the misc/index.md file title needs to be updated as well. I made the change. It should show properly now

**Comment by claire-braboszcz** [comment]
Thanks! I must have not saved it as I did change the index file and doubled checked it a few times... weird!
