### ISSUE TITLE
suggestion tutorial front page

### ISSUE THREAD

**Issue by claire-braboszcz** [sccn/sccn.github.io#39]
Maybe we could use this figure

https://sccn.ucsd.edu/wiki/File:RMC_SfN_poster_2018_2print.jpg

on this page 
https://sccn.github.io/

as a way to showcase all you can do with EEGLAB ?

Seems a shame not to put this cool figure forward!

**Comment by arnodelorme** [comment]
This one is a little too complex, but it is a good idea. I actually have the file to edit. Maybe we could put the chapter information in the file.
