### ISSUE TITLE
Detail section issue with Markdown links

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#40]
I do not think we can use links in "details" sections with this interpreter. See this section. The links are not properly formated (you have to load the page and scroll down to see the non formated links)

<img width="1126" alt="Screen Shot 2020-12-30 at 5 14 55 PM" src="https://user-images.githubusercontent.com/1872705/103392586-bd998d80-4ac2-11eb-8325-3492abc77064.png">

**Comment by arnodelorme** [comment]
Edited the page to remove details and fix the issue but the problem remains.

**Comment by dungscout96** [comment]
I saw you added the Table of content and the anchor links seem to work fine (clicking on the toc item scrolls to that specific section of the page). If it's about having hyperlink in collapsible paragraph using <details> tag, we have to use raw html (<a> tag), not markdown syntax.

**Comment by arnodelorme** [comment]
Ah OK, good to know. Thanks Dung.
