### ISSUE TITLE
Text alignment issue

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#47]
Is there a way to disable horizontal alignment?

https://sccn.github.io/workshops/reading_material.html

**Comment by dungscout96** [comment]
I set up so that when you add this at the beginning of the file, after the front matter:
```<script> jtd.setTheme('no-text-align'); </script>```
the text justify won't apply for that specific page anymore.
Otherwise, we can individually disable text alignment for a specific paragraph by using html <p style="text-align:left"> tag for it
