### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#49]
Probably a long shot, but just checking. Is there a way to fix the link issue

https://sccn.github.io/workshops/reading_material.html

With this theme, all linked text must be on one line. This is not a restriction of Markdown as the links are fine using another interpreter. Just checking.

**Comment by dungscout96** [comment]
A hack fix in b01b723 by adding ```<br>``` breaks manually but works on my end. I tried to look for a more elegant solution that applies to all hyperlinks but none seems to work.

**Comment by arnodelorme** [comment]
OK, I think I will just make the text links shorter. I tried to find a way to search text with long links but have not found a way yet (in visual studio, we can in theory search for regular expressions, but it does not seem functional).
