### ISSUE TITLE
Style for image alignment

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#5]
Allow images to be right aligned and embeded with text 

https://sccn.github.io/workshops/Online_EEGLAB_Workshop.html

**Comment by claire-braboszcz** [comment]
I could do some alignments using html + markdown but struggle to get the pictures really embedded. See the bottom of this page for example:
https://sccn.github.io/workshops/Online_EEGLAB_Workshop.html
Any insight welcome!

**Comment by dungscout96** [comment]
Applying either of these to the html <img> tag 
```
class="float-right" 
class="float-left"
```
should handle the alignment. Images in Markdown syntax will need to be converted to the html <img> format.
The word wrap might not be working for lines whose text is too long. But it should be fine for most cases
I applied the fix to the Online workshop page.
