### ISSUE TITLE
Table of content aspect

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#50]
Would it be possible to change the CSS to add a little bit of space above the "Table of content" header?

**Comment by arnodelorme** [comment]
<img width="768" alt="Screen Shot 2021-01-07 at 7 20 15 PM" src="https://user-images.githubusercontent.com/1872705/103977543-8f006000-511d-11eb-880f-8bfcfdb32904.png">

**Comment by dungscout96** [comment]
Should be able to, though I'm not seeing the Table of contents anymore. Did you decide to remove it?

**Comment by arnodelorme** [comment]
No, it is still there for me (toc.md) and I just push changes. Something on your side I think.
I will move the page tomorrow though (move the content to another page).

**Comment by dungscout96** [comment]
fixed in 2e5112b
