### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#52]
@dungscout96 would you mind having a look at the redirect on the 2021 EEGLAB workshop pages (menu Workshop). Is there a better way to have a link appear on the menu tab that creating an empty page with a redirect?

**Comment by dungscout96** [comment]
I modified it in 8449603 so that the redirect happens instantly. Let me know if you do want to show a white page with some message before the redirect happens though. I can do that too.

**Comment by arnodelorme** [comment]
Really cool. Thanks Dung.
