### ISSUE TITLE
Margin around image

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#53]
I have tried but was not really successful. The text is too close to the image on the newsletter page.

@dungscout96 , would you mind having a look?

**Comment by arnodelorme** [comment]
<img width="799" alt="Screen Shot 2021-01-10 at 4 14 08 PM" src="https://user-images.githubusercontent.com/1872705/104142306-20124980-535f-11eb-9b64-1acffda517d2.png">

**Comment by dungscout96** [comment]
I added the margin in 66eb26e. Can you see if that's good?

**Comment by arnodelorme** [comment]
Perfect. Thanks.
