### ISSUE TITLE
2 levels of menus

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#54]
@dungscout96, on the tutorial page, any chance your code could generate 2 levels of menu items instead of 1?

I mean instead of 4. Import data, we also have

a. Continuous data
b. Events
c. Channel Locations
d. BIDS

**Comment by arnodelorme** [comment]
<img width="1102" alt="Screen Shot 2021-01-10 at 9 32 16 PM" src="https://user-images.githubusercontent.com/1872705/104155861-2539bd80-538c-11eb-91ee-91e2ff2dbd71.png">

**Comment by dungscout96** [comment]
I implemented in 141ee5bfa227d43c543b1be8818e215ee13b2e83 and db289ef.

**Comment by arnodelorme** [comment]
That's really cool. I am impressed.
