### ISSUE TITLE
Workshop list not generated in index.markdown (main index)

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#56]
I have commented the automatically generated list and put a manual one for now. Has to do with mixing HTML and markdown.

**Comment by dungscout96** [comment]
This is because the workshops pages don't have long_title. I added check to use title when there's no long_title 7c4f8fb

**Comment by arnodelorme** [comment]
OK, I will add a long title.

**Comment by arnodelorme** [comment]
Fixed it and it is now functional. However, the short title is shown on the index.markdown, not sure why. I looked at toc_nav.html

**Comment by dungscout96** [comment]
I got the wrong syntax. Should work now

**Comment by arnodelorme** [comment]
Works now. Tx
