### ISSUE TITLE
Home link

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#7]
Change the home link on that page

https://github.com/sccn/sccn.github.io/blob/master/workshops/EEGLAB_2020_Lublin.md

I used an absolute HTTP link.
Not sure it is the way to reference home.

**Comment by dungscout96** [comment]
Where are you seeing that home link? I'm seeing the link to that page as https://sccn.github.io/workshops/EEGLAB_2020_Lublin.html

**Comment by dungscout96** [comment]
Claire might have fixed this
