### ISSUE TITLE
Online workshop page

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#9]
Issue with spacing of different line and also issue with BCILAB

<img width="883" alt="Screen Shot 2020-11-23 at 6 36 50 PM" src="https://user-images.githubusercontent.com/1872705/100049378-45e98c00-2dbb-11eb-8416-68f06ebeddbf.png">

**Comment by dungscout96** [comment]
Fixed in 40088c0e4eb418c961590ef971b72c3f90720243
